#!/usr/bin/env python3
"""
Generate realistic test data for RLWE circuit
Creates Prover.toml with proper witness values
"""

import random
import secrets

def sample_gaussian_discrete(sigma=10, bound=128):
    """Sample from discrete Gaussian distribution (simplified)"""
    # Simplified: sample uniform in [-bound, bound]
    # Real implementation would use discrete Gaussian
    return random.randint(-bound, bound-1)

def generate_prover_toml():
    """Generate Prover.toml with test data"""

    N = 1024
    MESSAGE_SLOTS = 32

    print("Generating test data...")

    # Messages (2 Field elements)
    msg_x = secrets.randbits(252)  # 252-bit random (safe for BN254)
    msg_y = secrets.randbits(252)

    # Witness: r (1024 coefficients)
    r = [sample_gaussian_discrete() for _ in range(N)]

    # Witness: e1_sparse (32 coefficients only!)
    e1_sparse = [sample_gaussian_discrete() for _ in range(MESSAGE_SLOTS)]

    # Witness: e2 (1024 coefficients)
    e2 = [sample_gaussian_discrete() for _ in range(N)]

    # Write to file
    with open('Prover.toml', 'w') as f:
        f.write("# Auto-generated test data for RLWE circuit\n")
        f.write("# Generated by generate_test_data.py\n\n")

        # Messages
        f.write("# Messages to encrypt (WaAddress.x and WaAddress.y)\n")
        f.write("messages = [\n")
        f.write(f'    "0x{msg_x:064x}",\n')
        f.write(f'    "0x{msg_y:064x}"\n')
        f.write("]\n\n")

        # Witness r
        f.write("# Witness: randomness r (1024 coefficients)\n")
        f.write("[witness.r]\n")
        f.write("coeffs = [\n")
        for i in range(0, N, 16):
            chunk = r[i:i+16]
            f.write("    " + ", ".join(str(x) for x in chunk))
            if i + 16 < N:
                f.write(",\n")
            else:
                f.write("\n")
        f.write("]\n\n")

        # Witness e1_sparse
        f.write("# Witness: sparse error e1 (32 coefficients only!)\n")
        f.write("e1_sparse = [\n")
        for i in range(0, MESSAGE_SLOTS, 16):
            chunk = e1_sparse[i:i+16]
            f.write("    " + ", ".join(str(x) for x in chunk))
            if i + 16 < MESSAGE_SLOTS:
                f.write(",\n")
            else:
                f.write("\n")
        f.write("]\n\n")

        # Witness e2
        f.write("# Witness: error e2 (1024 coefficients)\n")
        f.write("[witness.e2]\n")
        f.write("coeffs = [\n")
        for i in range(0, N, 16):
            chunk = e2[i:i+16]
            f.write("    " + ", ".join(str(x) for x in chunk))
            if i + 16 < N:
                f.write(",\n")
            else:
                f.write("\n")
        f.write("]\n")

    print(f"✅ Generated Prover.toml with:")
    print(f"   - Messages: 2 Field elements")
    print(f"   - r: {N} coefficients")
    print(f"   - e1_sparse: {MESSAGE_SLOTS} coefficients")
    print(f"   - e2: {N} coefficients")

if __name__ == "__main__":
    generate_prover_toml()
